<?php
    session_start();
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Main Menu</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="index.css">
</head>
<body>
<div align="right" style="size: 8px">
    <a  href="home.php">Back to the home page</a>
</div>
<p >Graduate Computer Science Department </p>
<p align="center">The University of Texas at Dallas </p>
<hr/>
<h2>Course List of Department</h2>
<h2>Computer Science</h2>
<table border="1" align="center">
    <tr><th>Course Number</th><th>Course Title</th><th>Course Description</th></tr>
    <tr><td>6301</td><td>Special Topics in Computer Science</td><td>Topics will vary.</td></tr>
    <tr><td>6304</td><td>Computer Architecture</td><td>Trends in processor, memory, I/O and system design.  Techniques for quantitative analysis and evaluation of computer systems to understand and compare alternative design choices in system design.  Components in high performance processors in computers: pipelining, instruction level parallelism, memory hierarchies, and input/output.  Students will undertake a major computing system analysis and design project.</td></tr>
    <tr><td>6320</td><td>Natural Language Processing</td><td>This course covers state-of-the-art methods for natural language processing.  After an introduction to the basics of syntax, semantic, and discourse analysis, the focus shifts to the integration of these modules into natural-language processing systems.  In addition to natural language understanding, the course presents advanced material on lexical knowledge acquisition, natural language generation, machine translation, and parallel processing of natural language.</td></tr>
    <tr><td>6321</td><td>Discourse Processing</td><td>Introduction to discourse processing from natural language texts.  Automatic clustering of utterances into coherent units.</td></tr>
    <tr><td>6322</td><td>Information Retrieval</td><td>This course covers modern techniques for storing and retrieving unformatted textual data and providing answers to natural language queries.  Current research topics and applications of information retrieval in data mining, data warehousing, text mining, digital libraries, hypertext, multimedia data, and query processing are also presented.</td></tr>
    <tr><td>6324</td><td>Information Security</td><td>A comprehensive study of security vulnerabilities in information systems and the basic techniques for developing secure applications and practicing safe computing. Topics include common attacking techniques such as buffer overflow, Trojan, virus, etc.  UNIX, Windows and Java security.  Conventional encryption. Hashing functions and data integrity.</td></tr>
    <tr><td>6325</td><td>Introduction to Bioinformatics</td><td>The course provides a broad overview of the bioinformatics field.  Comprehensive introduction to molecular biology and molecular genetics for a program of study in bioinformatics.  Discussion of elementary computer algorithms in biology</td></tr>
    <tr><td>6333</td><td>Algorithms in Computational Biology</td><td>The principles of algorithm design for biological datasets, and analysis of influential problems and techniques.  Biological sequence analysis, gene finding, RNA folding, protein folding, sequence alignment, genome assembly, comparative genomics, phylogenetics, clustering algorithms.</td></tr>
    <tr><td>6348</td><td>Data and Applications Security</td><td>The course will teach principles, technologies, tools and trends for data and applications security. Topics to be covered include: confidentiality, privacy and trust management; secure databases; secure distributed systems; secure multimedia and object systems; secure data warehouses; data mining for security applications; assured information sharing; secure knowledge management; secure collaboration; secure digital libraries; trustworthy semantic web; biometrics; digital forensics; secure e-commerce; secure sensor information management and secure social networks. Students will take one system or application and develop a secure version of that system or application for the programming project.</td></tr>
    <tr><td>6349</td><td>Network Security</td><td>This course covers theoretical and practical aspects of network security. The topics include use of cryptography for building secure communication protocols and authentication systems; security handshake pitfalls, Kerberos and PKI, security of TCP/IP protocols including IPsec, BGP security, VPNs, IDSes, firewalls, and anonymous routing; security of TCP/IP applications; wireless LAN security; denial-of-service defense. Students are required to do a programming project building a distributed application with certain secure communication features and required to participate in several network security lab exercises and cyber war games.</td></tr>
    <tr><td>6352</td><td>Performance of Computer Systems and Networks</td><td>Overview of case studies.  Quick review of principles of probability theory.  Queuing models and physical origin of random variables used in queuing models.  Various important cases of the M/M/m/N queuing system. Little\'s law.  The M/G/1 queuing system.  Simulation of queuing systems. Product form solutions of open and closed queuing networks.  Convolution algorithms and Mean Value Analysis for closed queuing networks.  Discrete time queuing systems.  Prerequisite: a first course on probability theory.</td></tr>
    <tr><td>6353</td><td>Compiler Construction</td><td>Lexical analyzers, context-free grammars.  Top-down and bottom-up parsing; shift reduce and LR parsing.  Operator-precedence, recursive-descent, predictive, and LL parsing. LR</td></tr>
    <tr><td>6354</td><td>Advanced Software Engineering</td><td>This course covers advanced theoretical concepts in software engineering and provides an extensive hands-on experience in dealing with various issues of software development.  It involves a semester-long group software development project spanning software project planning and management, analysis of requirements, construction of software architecture and design, implementation, and quality assessment.  The course will introduce formal specification, component-based software engineering, and software maintenance and evolution.</td></tr>
    <tr><td>6356</td><td>Software Maintenance, Evolution, and Re-Engineering</td><td>Principles and techniques of software maintenance.  Impact of software development process on software justifiability, maintainability, evolvability, and planning of release cycles.  Use of very high-level languages and dependencies for forward engineering and reverse engineering. Achievements, pitfalls, and trends in software reuse, reverse engineering, and re-engineering.</td></tr>
    <tr><td>6359</td><td>Object-Oriented Analysis and Design</td><td>Analysis and practice of modern tools and concepts that can help produce software that is tolerant of change.  Consideration of the primary tools of encapsulation and inheritance.  Construction of software-ICs which show the parallel with hardware construction.</td></tr>
    <tr><td>6360</td><td>Database Design</td><td>Methods, principles, and concepts that are relevant to the practice of database software design. Database system architecture; conceptual database models; relational and object-oriented databases; database system implementation; query processing and optimization; transaction processing concepts, concurrency, and recovery; security.</td></tr>
    <tr><td>6361</td><td>Advanced Requirements Engineering</td><td>System and software requirements engineering.  Identification, elicitation, modeling, analysis, specification, management, and evolution of functional and non-functional requirements.  Strengths and weaknesses of different techniques, tools, and object-oriented methodologies.  Interactions and trade-offs among hardware, software, and organization.  System and sub-system integration with software and organization as components of complex, composite systems.  Transition from requirements to design.  Critical issues in requirements engineering.</td></tr>
    <tr><td>6362</td><td>Advanced Software Architecture and Design</td><td>Concepts and methodologies for the development, evolution, and reuse of software architecture and design, with an emphasis on object-orientation. Identification, analysis, and synthesis of system data, process, communication, and control components.  Decomposition, assignment, and composition of functionality to design elements and connectors.  Use of non-functional requirements for analyzing trade-offs and selecting among design alternatives.  Transition from requirements to software architecture, design, and to implementation.</td></tr>
    <tr><td>6363</td><td>Design and Analysis of Computer Algorithms</td><td>The study of efficient algorithms for various computational problems.  Algorithm design techniques.  Sorting, manipulation of data structures, graphs, matrix multiplication, and pattern matching.  Complexity of algorithms, lower bounds, NP completeness.</td></tr>
    <tr><td>6365</td><td>Data and Text Mining for Computational Biology</td><td>The course introduces data and text mining as practiced currently in the bioinformatics field.  Major topics include: sequence alignment for determining similarity between proteins and genes; properties of similarities and distances; genomic, proteomic, and text databases in the real world; finding patterns</td></tr>
    <tr><td>6366</td><td>Computer Graphics</td><td>Device and logical coordinate systems.  Geometric transformations in two and three dimensions.  Algorithms for basic 2-D drawing primitives, such as Brensenham\'s algorithm for lines and circles, Bezier and B-Spline functions for curves, and line and polygon clipping algorithms.  Perspectives in 3-D, and hidden-line and hidden-face elimination, such as Painter\'s and Z-Buffer algorithms.</td></tr>
    <tr><td>6367</td><td>Software Testing, Validation and Verification</td><td>Fundamental concepts of software testing. Functional testing. GUI based testing tools. Control flow based test adequacy criteria. Data flow based test adequacy criteria.  White box based testing tools. Mutation testing and testing tools. Relationship between test adequacy criteria. Finite state machine based testing. Static and dynamic program slicing for testing and debugging. Software reliability. Formal verification of program correctness.</td></tr>
    <tr><td>6368</td><td>Telecommunication Network Management</td><td>In-depth study of network management issues and standards in telecommunication networks.  OSI management protocols including CMIP, CMISE, SNMP, and MIB.  ITU\'s TMN</td></tr>
    <tr><td>6369</td><td>Complexity of Combinatorial Algorithms</td><td>Topics include bounded reducibility and completeness, approximation algorithms and heuristics for NP-hard problems, randomized algorithms, additional complexity classes.</td></tr>
    <tr><td>6371</td><td>Advanced Programming Languages</td><td>Functional programming, Lambda calculus, logic programming, abstract syntax, denotational semantics of imperative languages, fixpoints semantics, verification of programs, partial evaluation, interpetation and automatic compilation, axiomatic semantics, applications of semantics to software engineering.</td></tr>
    <tr><td>6373</td><td>Intelligent Systems</td><td>Logical formalizations of knowledge for the purpose of implementing intelligent systems that can reason in a way that mimics human reasoning.  Topics include: syntax and semantics of common logic, description logic, modal epistemic logic; reasoning about uncertainties, beliefs, defaults and counterfactuals; reasoning within contexts; implementations of knowledge base and textual inference reasoning systems; and applications.</td></tr>
    <tr><td>6374</td><td>Computational Logic</td><td>Methods and algorithms for the solution of logic problems.  Topics include problem formulation in first order logic and extensions, theorem proving algorithms, polynomially solvable cases, logic programming, and applications.  Prerequisites: CS 5343, and knowledge of C.', '2015-06-01 04:27:33', '2015-06-01 04:27:33'),(42,'6375', 'CS', 'Machine Learning', 'Algorithms for training perceptions and multi-layer neural nets: back propagation, Boltzmann machines, and self-organizing nets. The ID3 and the Nearest Neighbor algorithms. Formal models for analyzing learnability: exact identification in the limit and probably approximately correct</td></tr>
    <tr><td>6376</td><td>Parallel Processing</td><td>Topics include parallel machine models, parallel algorithms for sorting, searching and matrix operations. Parallel graph algorithms.  Selected topics in parallel processing.</td></tr>
    <tr><td>6377</td><td>Introduction to Cryptography</td><td>This course covers the basic aspects of modern cryptography, including block ciphers, pseudorandom functions, symmetric encryption, Hash functions, message authentication, number-theoretic primitives, public-key encryption, digital signatures and zero knowledge proofs.</td></tr>
    <tr><td>6378</td><td>Advanced Operating Systems</td><td>Concurrent processing, inter-process communication, process synchronization, deadlocks, introduction to queuing theory and operational analysis, topics in distributed systems and algorithms, checkpointing, recovery, multiprocessor operating systems.</td></tr>
    <tr><td>6379</td><td>Biological Database Systems and Data Mining</td><td>Relational data models and database management systems; theories and techniques of constructing relational databases to store biological data, including sequences, structures, genetic linkages and maps, and signal pathways.  Introduction to a relational database query language</td></tr>
    <tr><td>6380</td><td>Distributed Computing</td><td>Topics include distributed algorithms, election algorithms, synchronizers, mutual exclusion, resource allocation, deadlocks, Byzantine agreement and clock synchronization, knowledge and common knowledge, reliability in distributed networks, proving distributed programs correct.</td></tr>
    <tr><td>6381</td><td>Combinatorics and Graph Algorithms</td><td>Fundamentals of combinatorics and graph theory.  Combinatorial optimization, optimization algorithms for graphs</td></tr>
    <tr><td>6382</td><td>Theory of Computation</td><td>Formal models of computation. Recursive function theory.  Undecidability and incompleteness.  Selected topics in theory of computation.  Prerequisite: Consent of Instructor.</td></tr>
    <tr><td>6383</td><td>Computational Systems Biology</td><td>The course will provide a system-level understanding of biological systems by analyzing biological data using computational techniques.  The major topics include: computational inference of biological networks</td></tr>
    <tr><td>6384</td><td>Computer Vision</td><td>Algorithms for extracting information from digital pictures.  Particular topics include: analysis of motion in time varying image sequences, recovering depth from a pair of stereo images, image separation, recovering shape from textured images and shadows, object matching techniques, model based recognition, the Hough transform.</td></tr>
    <tr><td>6385</td><td>Algorithmic Aspects of Telecommunication Networks</td><td>This is an advanced course on topics related to the design, analysis, and development of telecommunications systems and networks.  The focus is on the efficient algorithmic solutions for key problems in modern telecommunications networks, in centralized and distributed models.  Topics include: main concepts in the design of distributed algorithms in synchronous and asynchronous models, analysis techniques for distributed algorithms, centralized distributed solutions for handling design and optimization problems concerning network topology, architecture, routing, survivability, reliability, congestion, dimensioning and traffic management in modern telecommunication networks.</td></tr>
    <tr><td>6386</td><td>Telecommunication Software Design</td><td>Programming with sockets and remote procedure calls, real time programming concepts and strategies.  Operating system design for real time systems.  Encryption, file compression, and implementation of fire walls.  An in-depth study of TCP/IP implementation.  Introduction to discrete event simulation of networks. </td></tr>
    <tr><td>6387</td><td>Advanced Software Engineering Project</td><td>This course is intended to provide experience in a group project that requires advanced technical solutions, such as distributed multi-tier architectures, component-based technologies, automated software engineering, etc., for developing applications, such as web-based systems, knowledge-based systems, real-time systems, etc. The students will develop and maintain requirements, architecture and detailed design, implementation, and testing and their traceability relationships. Best practices in software engineering will be applied.</td></tr>
    <tr><td>6388</td><td>Software Project Planning and Management</td><td>Techniques and disciplines for successful management of software projects. Project planning and contracts.  Advanced cost estimation models.  Risk management process and activities.  Advanced scheduling techniques. Definition, management, and optimization of software engineering processes. Statistical process control.  Software configuration management.  Capability Maturity Model Integration</td></tr>
    <tr><td>6389</td><td>Formal Methods and Programming Methodology</td><td>Formal techniques for building highly reliable systems.  Use of abstractions for concisely and precisely defining system behavior.  Formal logic and proof techniques for verifying the correctness of programs. Hierarchies of abstractions, state transition models, Petri Nets, communicating processes.  Operational and definitional specification languages.  Applications to reliability-critical, safety-critical, and mission-critical systems, ranging from commercial computer communication systems to strategic command control systems.</td></tr>
    <tr><td>6390</td><td>Advanced Computer Networks</td><td>Survey of recent advancements in high-speed network technologies.  Application of quantitative approach to the study of broadband integrated networks including admission control, access control, and quality of service guarantee.</td></tr>
    <tr><td>6391</td><td>Optical Networks</td><td>Enabling technologies for optical networks.  Wavelength-division multiplexing. Broadcast-and-select optical networks. Wavelength-routed optical networks. Virtual topology design. Routing and wavelength assignment. Network control and management. Protection and restoration. Wavelength conversion. Traffic grooming. Photonic packet switching. Optical burst switching. Survey of recent advances in optical networking.</td></tr>
    <tr><td>6392</td><td>Mobile Computing Systems</td><td>Topics include coping with mobility of computing systems, data management, reliability issues, packet transmission, mobile IP, end-to-end reliable communication, channel and other resource allocation, slot assignment, routing protocols, and issues in mobile wireless networks</td></tr>
    <tr><td>6393</td><td>Advanced Algorithms in Biology</td><td>Recent advanced topics in algorithms in biology will be discussed.  Topics will be chosen from: sorting and transformational operations on strings and permutations, structural analysis of proteins, pooling design and nonadaptive group testing, approximation algorithms, and complexity issues.</td></tr>
    <tr><td>6394</td><td>Digital Telephony</td><td>Introduction and overview emphasizing the advantages of digital voice networks.  Voice digitization. Digital transmission, multiplexing, and switching.  Rearrangeable switching networks.  Digital modulation for radio systems.  Network operation issues: synchronization, control; integration of voice and data, packet switching and traffic analysis.</td></tr>
    <tr><td>6395</td><td>Speech Recognition, Synthesis, and Understanding</td><td>Basic speech processing techniques: isolated word recognition using dynamic time warping, acoustic modeling using hidden Markov models, statistical language modeling, search algorithms in large vocabulary continuous speech recognition, components in text-to-speech systems, architecture and components in spoken dialog systems.</td></tr>
    <tr><td>6396</td><td>Real-Time Systems</td><td>Introduction to real-time applications and concepts.  Real-time operating systems and resource management.  Specification and design methods for real-time systems.  System performance analysis and optimization techniques. Project to specify, analyze, design, implement and test small real-time system.</td></tr>
    <tr><td>6397</td><td>Synthesis and Optimization of High-Performance Systems</td><td>A comprehensive study of the high-level synthesis and optimization algorithms for designing high performance systems with multiple CPUs or functional units for critical applications such as Multimedia, Signal processing, Telecommunications, Networks, and Graphics applications, etc. Topics including algorithms for architecture-level synthesis, scheduling, resource binding, real-time systems, parallel processor array design and mapping, code generations for DSP processors, embedded systems and hardware/software codesigns.</td></tr>
    <tr><td>6398</td><td>DSP Architectures</td><td>Typical DSP algorithms, representation of DSP algorithms, data-graph, FIR filters, convolutions, Fast Fourier Transform, Discrete Cosine Transform, low power design, VLSI implementation of DSP algorithms, implementation of DSP algorithms on DSP processors, DSP applications including wireless communication and multimedia.</td></tr>
    <tr><td>6399</td><td>Parallel Architectures and Systems</td><td>A comprehensive study of the fundamentals of parallel systems and architecture. Topics including parallel programming environment, fine-grain parallelism such as VLIW and superscalar, parallel computing paradigm of shared-memory, distributed-memory, data-parallel and data-flow models, cache coherence, compiling techniques to improve parallelism, scheduling theory, loop transformations, loop parallelizations and run-time systems.</td></tr>
    <tr><td>7301</td><td>Recent Advances in Computing</td><td>Advanced topics and publications will be selected from the theory, design, and implementation issues in computing.  May be repeated for credit as topics vary.</td></tr>
</table>
<hr/>
<div id="footer" align="left">
    UNIVERSITY LINKS<br>
    <a href="course_list.php">Course List</a>
    <br>
    <a href="Acknowledgment.php">Acknowledgment of Policies Form</a>
    <div align="left">
        © The University of Texas at Dallas<br>
    </div>
</div>
</body>
</html>